### ISSUE TITLE
Error indexing Jira issues

### ISSUE THREAD

**Issue by OrlandoSoto** [cfpb/github-wiki-search#112]
Traceback (most recent call last):
  File "server/index.py", line 16, in <module>
    gh_repos, ghe_repos, jira_users, jira_projs = search.index()
  File "/home/ec2-user/github-wiki-search/server/search/__init__.py", line 23, in index
    jira_users, jira_projs = jira.index()
  File "/home/ec2-user/github-wiki-search/server/search/jira.py", line 48, in index
    'author': issue['fields']['creator']['name'],
TypeError: 'NoneType' object is unsubscriptable
Exception KeyError: KeyError(140382821633072,) in <module 'threading' from '/usr/lib64/python2.6/threading.pyc'> ignored

**Comment by OrlandoSoto** [comment]
steps to reproduce:

```
ssh ec2-user@10.153.97.166

cd /home/ec2-user/github-wiki-search

python server/index.py
```
the index script will run for several minutes and then will report the above error

**Comment by OrlandoSoto** [comment]
It seems to fail at SSL certificate verification on the search.demo server though I was able to run this in my local environment.

**Comment by OrlandoSoto** [comment]
The SSL issue has been resolved. It turned out to be a problem with the docker-machine I created. I used a different docker-machine and ran without SSL issues.

**Comment by OrlandoSoto** [comment]
The Jira indexing issue was fixed in this commit: https://github.com/cfpb/github-wiki-search/commit/0460a6ed99f42a7505bb47e1e7dd2fc6acc0d068
